media_player:
  - platform: universal
    name: Bedroom TV
    children:
      - media_player.bedroom_speaker
    commands:
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.bedroom_tv_power
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.bedroom_tv_power
      volume_up:
        service: script.turn_on
        data:
          entity_id: script.bedroom_volume_up_script
      volume_down:
        service: script.turn_on
        data:
          entity_id: script.bedroom_volume_down_script
      volume_mute:
        service: script.turn_on
        data:
          entity_id: script.projector_mute_script
    attributes:
      is_volume_muted: switch.bedroom_tv_mute
      state: switch.bedroom_tv_power

timer:
  bedroom_timer:
    name: Bedroom Timer
    duration: '00:45:00'

binary_sensor:
  platform: template
  sensors:
    bedroom_tv_power_outlet:
      value_template: "{{ states.switch.outlet_bedroom_tv.attributes.current_power_w.split(' ')[0] | int > 5  }}"

script:
  bedroom_timer_script:
    alias: Start Bedroom TV Timer
    sequence:
      service: timer.start
      data:
        entity_id: timer.bedroom_timer
        duration: 1800
