automation:
  - alias: Turn Off Kitchen Light
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupancy
        to: 'off'
        for:
          seconds: 60
    action:
      service: light.turn_off
      data:
        entity_id: light.kitchen

binary_sensor:
  platform: template
  sensors:
    kitchen_occupancy:
      value_template: "{{ is_state('input_boolean.kitchen_motion','on') }}"
      delay_off:
        minutes: 11

input_boolean:
  kitchen_motion:
    initial: off

